=== Huyen0306/docs/Lộn xộn 2/booking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="khachsan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="madon" type="xs:string"></xs:element>
                <xs:element name="ten" type="xs:string"></xs:element>
                <xs:element name="ngaynhan" type="xs:date"></xs:element>
                <xs:element name="ngaytra" type="xs:date"></xs:element>
                <xs:element name="dsphong">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="phong" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="loai" type="xs:string"></xs:element>
                                        <xs:element name="sodem" type="xs:integer"></xs:element>
                                        <xs:element name="gia" type="xs:nonNegativeInteger"></xs:element>
                                        <xs:element name="thanhtien" type="xs:nonNegativeInteger"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>   
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tongtien" type ="xs:nonNegativeInteger"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Huyen0306/docs/Lộn xộn 2/booking.xml
<?xml version="1.0" encoding="UTF-8"?>
<khachsan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="booking.xsd">
    <madon>ks001</madon>
    <ten>Nguyễn Văn A</ten>
    <ngaynhan>2025-09-15</ngaynhan>
    <ngaytra>2025-09-20</ngaytra>
    <dsphong>
        <phong>
            <loai>Đơn</loai>
            <sodem>4</sodem>
            <gia>200000</gia>
            <thanhtien>800000</thanhtien>
        </phong>
        <phong>
            <loai>Đôi</loai>
            <sodem>3</sodem>
            <gia>400000</gia>
            <thanhtien>1200000</thanhtien>
        </phong>
    </dsphong>
    <tongtien>2000000</tongtien>
</khachsan>
