=== Huyen0306/docs/Lộn xộn/donhang.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="donhang">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="madonhang">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="6" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="ngaydathang" type="xs:date" />
                <xs:element name="hoten" type="xs:string" />
                <xs:element name="diachi" type="xs:string" />
                <xs:element name="sanpham" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tensp" type="xs:string" />
                            <xs:element name="soluong">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="1" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="giatien" type="xs:double" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Huyen0306/docs/Lộn xộn/donhang.xml
<?xml version="1.0" encoding="UTF-8"?>
<donhang xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="donhang.xsd">
    <madonhang>DH0001</madonhang>
    <ngaydathang>2025-10-20</ngaydathang>
    <hoten>Phan Bá Đủ</hoten>
    <diachi>12 Phan Chu Trinh,Phường thuận hóa, TP.Huế</diachi>
    <sanpham>
        <tensp>Chuột không dây Logitech</tensp>
        <soluong>1</soluong>
        <giatien>250000</giatien>
    </sanpham>
</donhang>
